repository:
  savePath: "./data/urls.json"
  inMemory: false
server:
  hostAddress: "localhost:8080"
  accuralSystemAddress: "localhost:8090"
database:
  host: "localhost"
  port: "5432"
  dbname: "store"
  user: "store"
  password: "admin"
auth:
  tokenExp: 10800
  secretKey: "mySecretKey"
worker:
  workersCount: 2
  bufferSize: 100
  errMaximumAmount: 100